### ISSUE TITLE
Add support for using Python 3.13

### ISSUE THREAD

**Issue by junoriosity** [valkey-io/libvalkey-py#27]
Is it possible to use Python 3.13?

If so, how can we do it?

**Comment by aiven-sal** [comment]
Hi, there is no stable release yet, but there is a beta with 3.13 support https://github.com/valkey-io/libvalkey-py/releases/tag/v4.0.1b3

**Comment by mkmkme** [comment]
So, to install the version currently supporting Python 3.13, you can invoke `pip install libvalkey==4.0.1b3` explicitly. 
Version 4.0.1 will be released soon and it will support 3.13.

**Comment by mkmkme** [comment]
Hey @junoriosity,

libvalkey 4.0.1 has just been released. It supports Python 3.13. 
You can install it simply via `pip install libvalkey`. 

I'll close this ticket now. If you have any issues with the release, feel free to open a new one!

**Comment by mkmkme** [comment]
@junoriosity the latest release of valkey-py unfortunately doesn't support Python 3.13 yet.
We're currently working on a new release that will support it. We will release the new beta very soon and I'll get back to you with the valkey-py version you can use

**Comment by junoriosity** [comment]
@mkmkme Thanks a lot for letting me know, I am very much looking forward to it  🙂
